// lib/types.ts
// Core TypeScript types for AMath Tutor

import { Database } from './database.types'; // Auto-generated by Supabase CLI

// ============================================================================
// USER TYPES
// ============================================================================

export type UserRole = 'tutor' | 'student';

export interface Profile {
  id: string;
  role: UserRole;
  full_name: string;
  created_at: string;
  updated_at: string;
}

export type ThemePreference = 'light' | 'dark' | 'system';

export interface UserPreferences {
  user_id: string;
  show_latex: boolean;
  show_explanations: boolean;
  auto_save: boolean;
  theme: ThemePreference;
  preferences: Record<string, any>; // Flexible JSON for additional settings
  created_at: string;
  updated_at: string;
}

export interface QuizSession {
  id: string;
  quiz_id: string;
  student_id: string;
  current_question: number;
  time_remaining_seconds: number | null;
  session_data: Record<string, any>; // Flexible session state
  last_activity: string;
  created_at: string;
}

// ============================================================================
// QUIZ TYPES
// ============================================================================

export type QuizTopic = 
  | 'A1' // Quadratic functions
  | 'A2' // Equations and inequalities
  | 'A3' // Surds
  | 'A4' // Polynomials and partial fractions
  | 'A5' // Binomial expansions
  | 'A6' // Exponential and logarithmic functions
  | 'G1' // Trigonometric functions, identities and equations
  | 'G2' // Coordinate geometry in two dimensions
  | 'G3' // Proofs in plane geometry
  | 'C1'; // Differentiation and integration

export const TOPIC_NAMES: Record<QuizTopic, string> = {
  A1: 'Quadratic Functions',
  A2: 'Equations and Inequalities',
  A3: 'Surds',
  A4: 'Polynomials and Partial Fractions',
  A5: 'Binomial Expansions',
  A6: 'Exponential and Logarithmic Functions',
  G1: 'Trigonometric Functions',
  G2: 'Coordinate Geometry',
  G3: 'Proofs in Plane Geometry',
  C1: 'Calculus',
};

export type QuizDifficulty = 'foundational' | 'intermediate' | 'exam_level';

export type QuestionType = 'mcq' | 'multi_select';

// ============================================================================
// QUESTION TYPES
// ============================================================================

interface BaseQuestion {
  id: number;
  question: string; // LaTeX supported via KaTeX
  marks: number;
  explanation?: string;
}

export interface MCQQuestion extends BaseQuestion {
  type: 'mcq';
  options: [string, string, string, string]; // Exactly 4 options
  correctAnswer: 'A' | 'B' | 'C' | 'D';
}

export interface MultiSelectQuestion extends BaseQuestion {
  type: 'multi_select';
  options: string[]; // Variable number of options
  correctAnswers: string[]; // Array of correct option letters (e.g., ['A', 'C'])
  partialCredit: boolean; // Award partial marks for partially correct answers
}

export type Question = MCQQuestion | MultiSelectQuestion;

// ============================================================================
// QUIZ UPLOAD SCHEMA
// ============================================================================

export interface QuizUploadPayload {
  title: string;
  topic: QuizTopic;
  week: number;
  difficulty: QuizDifficulty;
  time_limit_minutes: number;
  due_date: string; // ISO 8601 format
  questions: Question[];
}

// ============================================================================
// QUIZ DATABASE TYPES
// ============================================================================

export interface Quiz {
  id: string;
  title: string;
  topic: QuizTopic;
  week: number;
  difficulty: QuizDifficulty;
  time_limit_minutes: number;
  due_date: string;
  total_marks: number;
  questions: Question[];
  created_by: string;
  published: boolean;
  created_at: string;
  updated_at: string;
}

export interface QuizListItem {
  id: string;
  title: string;
  topic: QuizTopic;
  week: number;
  difficulty: QuizDifficulty;
  due_date: string;
  total_marks: number;
  published: boolean;
  attempt?: QuizAttemptSummary; // For student view
}

// ============================================================================
// QUIZ ATTEMPT TYPES
// ============================================================================

export interface StudentAnswer {
  question_id: number;
  answer: string | string[]; // Single string for MCQ, array for multi-select
  time_spent_seconds: number;
}

export interface QuizAttempt {
  id: string;
  quiz_id: string;
  student_id: string;
  started_at: string;
  submitted_at?: string;
  answers: StudentAnswer[];
  score?: number;
  total_marks?: number;
  time_taken_seconds?: number;
  completed: boolean;
  created_at: string;
}

export interface QuizAttemptSummary {
  id: string;
  started_at: string;
  submitted_at?: string;
  score?: number;
  total_marks?: number;
  completed: boolean;
}

// ============================================================================
// QUESTION RESULT TYPES (Mistake Journal)
// ============================================================================

export interface QuestionResult {
  id: string;
  attempt_id: string;
  question_index: number;
  question_text: string;
  topic: QuizTopic;
  question_type: QuestionType;
  student_answer: string | string[];
  correct_answer: string | string[];
  is_correct: boolean;
  marks_awarded: number;
  marks_possible: number;
  created_at: string;
}

export interface MistakesByTopic {
  topic: QuizTopic;
  topic_name: string;
  mistakes: QuestionResult[];
  total_questions: number;
  incorrect_questions: number;
  accuracy_rate: number;
}

// ============================================================================
// ANALYTICS TYPES
// ============================================================================

export interface TopicMastery {
  topic: QuizTopic;
  topic_name: string;
  total_questions: number;
  correct_questions: number;
  accuracy_rate: number;
  average_score: number;
  quizzes_completed: number;
}

export interface StudentAnalytics {
  total_quizzes: number;
  completed_quizzes: number;
  average_score: number;
  total_time_spent_minutes: number;
  topic_mastery: TopicMastery[];
  recent_mistakes: QuestionResult[];
  completion_rate: number;
}

export interface TutorDashboard {
  total_quizzes: number;
  published_quizzes: number;
  pending_reviews: number; // Completed but not viewed by tutor
  student_progress: StudentAnalytics;
  recent_attempts: QuizAttemptWithQuiz[];
}

export interface QuizAttemptWithQuiz extends QuizAttempt {
  quiz: {
    title: string;
    topic: QuizTopic;
    total_marks: number;
  };
}

// ============================================================================
// FORM VALIDATION TYPES
// ============================================================================

export interface QuizValidationError {
  field: string;
  message: string;
}

export interface QuizValidationResult {
  valid: boolean;
  errors: QuizValidationError[];
  total_marks?: number;
}

// ============================================================================
// API RESPONSE TYPES
// ============================================================================

export interface APIResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  page: number;
  per_page: number;
  total: number;
  total_pages: number;
}

// ============================================================================
// NOTIFICATION TYPES
// ============================================================================

export type NotificationType = 
  | 'quiz_assigned'
  | 'quiz_submitted'
  | 'quiz_graded'
  | 'quiz_overdue'
  | 'deadline_reminder';

export interface Notification {
  id: string;
  type: NotificationType;
  title: string;
  message: string;
  read: boolean;
  created_at: string;
  related_id?: string; // quiz_id or attempt_id
}

// ============================================================================
// REALTIME TYPES
// ============================================================================

export interface QuizAttemptProgress {
  attempt_id: string;
  quiz_id: string;
  student_id: string;
  current_question: number;
  total_questions: number;
  time_remaining_seconds: number;
  answers_saved: number;
}

// ============================================================================
// UTILITY TYPES
// ============================================================================

export type SortOrder = 'asc' | 'desc';

export interface SortConfig {
  field: string;
  order: SortOrder;
}

export interface FilterConfig {
  topic?: QuizTopic[];
  difficulty?: QuizDifficulty[];
  week?: number[];
  published?: boolean;
  completed?: boolean;
}
